import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Geist } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'nextjs-firebase-auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${geistSans.variable} antialiased`}>
          <Toaster />
          {children}
        </body>
      </SessionProvider>
    </html>
  )
}
